name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      SYSROOT: ${{ github.workspace }}/pi-sysroot
      
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gcc
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: >
        -L ${{ github.workspace }}/pi-sysroot/usr/lib
        -L ${{ github.workspace }}/pi-sysroot/lib
        -C target-feature=-crt-static
        -C link-arg=-fuse-ld=lld
        -C target-cpu=cortex-a53

      PKG_CONFIG_ALLOW_CROSS_aarch64_unknown_linux_musl: "1"
      PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_musl: ${{ github.workspace }}/pi-sysroot
      PKG_CONFIG_PATH_aarch64_unknown_linux_musl: ${{ github.workspace }}/pi-sysroot/usr/lib/pkgconfig
      PKG_CONFIG_ALL_DYNAMIC: "1"

      BINDGEN_EXTRA_CLANG_ARGS: >
        --sysroot=${{ github.workspace }}/pi-sysroot
        -I${{ github.workspace }}/pi-sysroot/usr/include
        -I${{ github.workspace }}/pi-sysroot/usr/include/c++/15.2.0
        -I${{ github.workspace }}/pi-sysroot/usr/include/c++/15.2.0/aarch64-alpine-linux-musl

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-musl

      - name: Install LLD Linker
        run: sudo apt-get update && sudo apt-get install -y lld

      - name: Download and setup Bootlin aarch64-musl cross-compiler
        run: |
          wget https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--musl--stable-2025.08-1.tar.xz
          sudo tar -xf aarch64--musl--stable-2025.08-1.tar.xz -C /opt
          cd /opt/aarch64--musl--stable-2025.08-1
          sudo ./relocate-sdk.sh
          echo "/opt/aarch64--musl--stable-2025.08-1/bin" >> $GITHUB_PATH

      - name: Extract minimal pi-sysroot
        run: |
          mkdir -p ${{ github.workspace }}/pi-sysroot
          tar -xzvf ci/raspi-vision-minimal-sysroot.tar.gz -C ${{ github.workspace }}/pi-sysroot

      - name: Remove local Cargo config
        run: rm -f .cargo/config.toml

      - name: Build for Alpine (Release)
        run: cargo build --release --target aarch64-unknown-linux-musl

      - name: Rename binary for release
        run: mv target/aarch64-unknown-linux-musl/release/raspi-vision raspi-vision-aarch64-musl

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: raspi-vision-aarch64-musl
